### ISSUE TITLE
create an index of communities

### ISSUE THREAD

**Issue by SaranjeetKaur** [EllaKaye/communers#1]
Collect community names, their website URLs, a short description of what they do, and any relevant tags in the [HackMD](https://hackmd.io/xkogXQFyRyeQmgA9s7xxEw?both).

**Comment by parnumeric** [comment]
Do you agree with using abbreviations in place of tags (level, domain, special interest) for brevity or any other suggestions?

**Comment by SaranjeetKaur** [comment]
This is transferred to a CSV file for now
