### ISSUE TITLE
RSEcon BoF session

### ISSUE THREAD

**Issue by thomaszwagerman** [EllaKaye/communers#34]
Thoughts for the group, is there potential for an RSEcon Birds of a Feather session for "Community Builders"?

https://rsecon24.society-rse.org/calls/interactive-sessions/

**Comment by alessandrofelder** [comment]
I think it's a great idea (but am unfortunately unlikely to attend RSECon this year... in-person at least)

**Comment by rowlandm** [comment]
I'm "borrowing" this idea for Asian colleagues doing conferences in open source, research software, and research infrastructure!

**Comment by EllaKaye** [comment]
Thanks for the suggestion @thomaszwagerman. There's definitely potential but I, too, am unlikely to attend RSECon in person, though likely will be remote. I don't think I'll have a chance to pull a proposal together by the deadline. If someone else is willing to take the lead on this, I'd be happy to support.

**Comment by thomaszwagerman** [comment]
I'll see what I can put together today, they did extend the deadline for CW24 but it is tomorrow (yikes).

**Comment by thomaszwagerman** [comment]
Because we all have access to this document, I've put a draft abstract at the bottom of this document:

[Hackday Idea Document](https://docs.google.com/document/d/1wQhUGqiBA_06qOJxGvLAS7Apz9FPII5s6GbfnWwu0bU/edit#heading=h.yqnxsg1girps)

It is very rough and still work in progress (pulled it together from various bits we already wrote). Any input/feedback would be very welcome. I will pick it up again later this afternoon.

**Comment by jnywong** [comment]
Hey @thomaszwagerman thanks for driving this forward! I am attending RSECon24 this year and am keen to see this in the programme.

I've added a comment to the doc, but I am also submitting an abstract for a talk by the deadline today so happy to let you to take the driving seat with this one and generally help where needed 👍

**Comment by thomaszwagerman** [comment]
Thanks @jnywong, I appreciate that.

Because of the time constraint I've put it together, but in my view this is **our** abstract (in no small part because a large part is copied from the website, I didn't write it). 

What I mean by that is I'm happy to submit it, but would also be happy for someone else to lead on the submission now we have an outline written. From RSEcon guidance, remote attendance is not a barrier to this (they ask at least one person is in the room, I'd be happy to be that person). Just putting that out there before we proceed :).

Second point, to submit an abstract we need **explicit** permission from each listed author, as well as email, affiliation, country, and ORCID (optional). @EllaKaye @jnywong , I'm taking your support above as you being happy to be "on the bill" as authors but do stop me if that is not the case. 

Are any of @SaranjeetKaur @alessandrofelder @parnumeric @rowlandm @mdbarker @habuabba keen to be part of this submission, through contribution to conference material or RSEcon attendance (whether in-person or remote), and be listed as an author on this abstract? IMO regardless of RSEcon involvement your contributions will be acknowledged in the materials themselves.

**Comment by alessandrofelder** [comment]
@thomaszwagerman I'd be happy to help organise materials for the workshop and be listed as an author - I don't think I have time today for more than a quick review of the abstract if that's OK?

**Comment by SaranjeetKaur** [comment]
@thomaszwagerman - I am happy to help organise and be listed as an author. I will go through the abstract now.

**Comment by habuabba** [comment]
Thank you so much @thomaszwagerman and all other members of the team. I am more than happy to be part. I can commit myself to the in-person representation. However, I can only be available to work on the submission after Thursday, the 9th of May. My details are:

**Comment by habuabba** [comment]
Thank you so much @thomaszwagerman  and all other members of the team. I am more than happy to be part. I can commit myself to the in-person representation. However, I can only be available to work on the submission after Thursday, the 9th of May. My details are:
\author{Adamu Adamu Habu}
\email{aah5@st-andrews.ac.uk}
\orcid{0000-0003-0197-7676}
\affiliation{%
  \institution{School of Computer Science, University of St Andrews}
  \streetaddress{Jack Cole Building, North Haugh}
  \city{St Andrews}
  \state{Scotland}
  \country{Scotland, United Kingdom}
  \postcode{KY16 9SX}
}

**Comment by EllaKaye** [comment]
Hello. Thanks so much for pulling this together @thomaszwagerman, especially last minute :) 

I'm definitely happy to be listed on this, and, if the abstract is successful, to help organise/run the workshop. I will definitely attend, either in person or remote.

I'll put my details in the Slack.

**Comment by SaranjeetKaur** [comment]
@thomaszwagerman and Everyone here - I am thinking if we can align the proposal so that the structure is that of a community sprint to develop CommuneRS and to document and develop the [International RSE Community handbook](https://rse-worldwide.github.io/RSE-Community-Building/intro.html). 

Developing the handbook was proposed at the RSE Worldwide session that I was co-organising last year for RSECon23. I feel these are parallel ideas and could develop together. Let me know what you think!

**Comment by parnumeric** [comment]
Hi @thomaszwagerman and everyone, amazing to see the efforts towards submission. I'll also be happy to get involved through contribution and attendance (I'm also planning to attend RSECon), but today and I guess tomorrow I'll be busy writing my abstract for a poster, too. I'll provide my details for co-authorship in Slack.

**Comment by thomaszwagerman** [comment]
@SaranjeetKaur I think the contribution sprint structure lends itself well to contributions to the International RSE Community handbook (and possibly other community initiatives), so I am happy to include that.

With regards to the content plan, I think some pre-prepared lighting talks to share some community building journeys would be nice to set the scene, and give a platform to communities. I think there is a wide range of communities already represented in this group we can draw from. 

Having said that, I think the content plan is just for the sake of the submission, and I estimated the timings. So, we can adjust the timings to allow for more "sprint" (or all sprint, no talk :grin:) time if we want, post-submission.

There is also an option to move from 75 minutes to 150 minutes, but I think that may be too much.

With an eye on the deadline tomorrow and the abstract word count, I've incorporated your paragraph on the international handbook into the rest of the text to balance the focus between communers and the international handbook. Let me know what you think.

**Comment by SaranjeetKaur** [comment]
Thanks @thomaszwagerman! It all makes sense to me and looks like we can go ahead and submit it unless anybody wants to add/edit anything.

**Comment by SaranjeetKaur** [comment]
I would say let's allow everyone time until 12:00 UTC tomorrow before we submit. @rowlandm and @mdbarker are in Australian timezone so not sure if they followed this discussion today.

**Comment by mdbarker** [comment]
Thanks all. I'll be at RSECon and happy to be involved. My organisation, ReSA, does convene [Community Leaders Forums](https://www.researchsoft.org/community-forum/) on an ad-hoc basis (currently 2-3 a year) so it'd be great to connect these pieces. I also spoke to Sandra Gesing yesterday, Director of US-RSE. She recently started facilitating a group of community leaders discussing community building practices, it's currrently just a small and informal group, which she hopes to open up and grow. She had previously started [COCO](https://coco.cyberinfrastructure.org/), another community of communities initiative which is very similar to ours , but it's no longer active, but she'd be interested to join the discussion - and she'll be at RSECon.

**Comment by thomaszwagerman** [comment]
Thank you all for your swift responses!

We're past 12:00 UTC, so I will make a start with the submission now.

If anyone who wanted to be a part of this, but has missed this discussion prior to the deadline (entirely reasonable given the timeframe, taking some time off after the workshop, and a bank holiday here in the UK), I asked whether authors can be added post-submission:

> After submitting you can edit your submission, but I would assume this is not possible during the review period and may not be possible afterwards. If necessary the programme team has access to modify submissions, just send an email to [rsecon24-programme-team@society-rse.org](mailto:rsecon24-programme-team@society-rse.org) with the required details.

So I would say from that, you can still be added but possibly not after we've been (**fingers crossed**) accepted. I think review will take place until the end of May.

**Comment by thomaszwagerman** [comment]
Submitted, fingers crossed, thank you all!

I will add a markdown file with the abstract for future reference - not today though :grin:!

**Comment by EllaKaye** [comment]
Amazing work @thomaszwagerman 😄 Thanks for taking the lead on this and getting it done, and to everyone else who contributed. I'm so happy and excited to see the momentum on communeRS post-CW24 and looking forward to seeing where it goes from here (and being part of that too).
